/**
 * Agentic AI Task Service
 *
 * Manages autonomous AI-driven remediation tasks that draft policy updates,
 * route approvals, and execute compliance actions without manual intervention.
 */
import { getDb } from "./db";
import { agenticTasks, policies, regulatoryUpdates, users, aiRecommendations } from "../drizzle/schema";
import { eq, desc, and } from "drizzle-orm";
import { invokeLLM } from "./_core/llm";
import { createAuditEntryWithHash } from "./auditCache";
import { getDb as getDbDirect } from "./db";
import { drizzle } from "drizzle-orm/mysql2";

export async function getAgenticTasks(filters?: { status?: string; assignedTo?: number }) {
  const db = await getDb();
  if (!db) return [];
  const conditions = [];
  if (filters?.status) conditions.push(eq(agenticTasks.status, filters.status as any));
  if (filters?.assignedTo) conditions.push(eq(agenticTasks.assignedTo, filters.assignedTo));
  return conditions.length > 0
    ? db.select().from(agenticTasks).where(and(...conditions)).orderBy(desc(agenticTasks.createdAt))
    : db.select().from(agenticTasks).orderBy(desc(agenticTasks.createdAt));
}

export async function createAgenticTask(data: {
  taskType: "policy_draft" | "policy_update" | "gap_remediation" | "evidence_collection" | "report_generation" | "notification_send";
  title: string;
  description?: string;
  triggeredBy: "ai_recommendation" | "regulatory_update" | "manual" | "scheduled";
  sourceId?: number;
  sourceType?: string;
  assignedTo?: number;
  priority?: "low" | "medium" | "high" | "urgent";
}) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");
  const [result] = await db.insert(agenticTasks).values({
    ...data,
    status: "queued",
    priority: data.priority || "medium",
  });
  return { id: (result as any).insertId };
}

export async function executeAgenticTask(taskId: number) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const [task] = await db.select().from(agenticTasks).where(eq(agenticTasks.id, taskId)).limit(1);
  if (!task) throw new Error("Task not found");

  await db.update(agenticTasks).set({ status: "in_progress" }).where(eq(agenticTasks.id, taskId));

  try {
    let aiGeneratedContent = "";

    if (task.taskType === "policy_draft" || task.taskType === "policy_update") {
      // Get context from source
      let context = task.description || "";
      if (task.sourceType === "regulatory_update" && task.sourceId) {
        const [update] = await db.select().from(regulatoryUpdates).where(eq(regulatoryUpdates.id, task.sourceId)).limit(1);
        if (update) context = `Regulatory Update: ${update.title}\n${update.summary}\nImpact: ${update.impactLevel}`;
      }

      const response = await invokeLLM({
        messages: [
          {
            role: "system",
            content: "You are a UK regulatory compliance expert. Draft professional, legally sound policy content aligned with UK regulatory requirements (FCA, PRA, ICO). Use formal language appropriate for a regulated UK financial services firm."
          },
          {
            role: "user",
            content: `Task: ${task.title}\nContext: ${context}\n\nDraft a comprehensive policy section (300-400 words) that addresses this requirement. Include: Purpose, Scope, Policy Statement, Responsibilities, and Review Schedule.`
          }
        ],
      });
      aiGeneratedContent = String(response);
    } else if (task.taskType === "gap_remediation") {
      const response = await invokeLLM({
        messages: [
          {
            role: "system",
            content: "You are a UK regulatory compliance expert. Provide specific, actionable gap remediation steps."
          },
          {
            role: "user",
            content: `Gap Remediation Task: ${task.title}\nDescription: ${task.description}\n\nProvide 5 specific, actionable remediation steps with UK regulatory references and estimated completion timeframes.`
          }
        ],
      });
      aiGeneratedContent = String(response);
    } else if (task.taskType === "report_generation") {
      aiGeneratedContent = `Automated Report Generated: ${task.title}\nGenerated at: ${new Date().toISOString()}\nStatus: Complete\nThis report was automatically generated by the RegulaSync Agentic AI engine.`;
    } else {
      aiGeneratedContent = `Task "${task.title}" processed by Agentic AI at ${new Date().toISOString()}.`;
    }

    await db.update(agenticTasks)
      .set({
        status: "awaiting_approval",
        aiGeneratedContent,
      })
      .where(eq(agenticTasks.id, taskId));

    return { success: true, status: "awaiting_approval", aiGeneratedContent };
  } catch (error) {
    await db.update(agenticTasks)
      .set({ status: "failed", errorMessage: String(error) })
      .where(eq(agenticTasks.id, taskId));
    throw error;
  }
}

export async function approveAgenticTask(taskId: number, approvedBy: number) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");
  await db.update(agenticTasks)
    .set({ status: "completed", approvedBy, approvedAt: new Date(), completedAt: new Date() })
    .where(eq(agenticTasks.id, taskId));

  const dbConn = await getDbDirect();
  if (dbConn) {
    await createAuditEntryWithHash(dbConn, {
      userId: approvedBy,
      action: "approve",
      entityType: "agentic_task",
      entityId: taskId,
      userName: "System",
    });
  }

  return { success: true };
}

export async function rejectAgenticTask(taskId: number, rejectedBy: number, reason?: string) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");
  await db.update(agenticTasks)
    .set({ status: "rejected", errorMessage: reason || "Rejected by reviewer" })
    .where(eq(agenticTasks.id, taskId));
  return { success: true };
}

export async function triggerAgenticTasksFromUpdate(regulatoryUpdateId: number, userId: number) {
  const db = await getDb();
  if (!db) return [];

  const [update] = await db.select().from(regulatoryUpdates).where(eq(regulatoryUpdates.id, regulatoryUpdateId)).limit(1);
  if (!update) return [];

  const tasks = [];

  // Auto-create a policy update task
  if (update.impactLevel === "high" || update.impactLevel === "critical") {
    const task = await createAgenticTask({
      taskType: "policy_update",
      title: `Auto-update policies for: ${update.title}`,
      description: `Regulatory update from ${update.regulatoryBody} requires policy review and update. Summary: ${update.summary}`,
      triggeredBy: "regulatory_update",
      sourceId: regulatoryUpdateId,
      sourceType: "regulatory_update",
      assignedTo: userId,
      priority: update.impactLevel === "critical" ? "urgent" : "high",
    });
    tasks.push(task);
  }

  // Auto-create a gap remediation task
  const gapTask = await createAgenticTask({
    taskType: "gap_remediation",
    title: `Gap analysis remediation: ${update.title}`,
    description: `Identify and remediate compliance gaps arising from: ${update.title}`,
    triggeredBy: "regulatory_update",
    sourceId: regulatoryUpdateId,
    sourceType: "regulatory_update",
    assignedTo: userId,
    priority: "medium",
  });
  tasks.push(gapTask);

  return tasks;
}
