/**
 * Report Generation Service
 * 
 * Generates PDF and CSV reports for compliance, audit trails, and policies.
 * Uses real database data and proper formatting.
 */

import { getDb } from "./db";
import { 
  policies, 
  complianceRecords, 
  auditTrail, 
  regulatoryUpdates,
  aiRecommendations,
  users,
  delegationAuthority
} from "../drizzle/schema";
import { eq, desc, and, gte, lte, sql } from "drizzle-orm";

/**
 * Generate CSV content from data
 */
function generateCSV(headers: string[], rows: string[][]): string {
  const escapeCSV = (value: string | null | undefined): string => {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const headerLine = headers.map(escapeCSV).join(',');
  const dataLines = rows.map(row => row.map(escapeCSV).join(','));
  
  return [headerLine, ...dataLines].join('\n');
}

/**
 * Generate HTML report template
 */
function generateHTMLReport(title: string, content: string, metadata: Record<string, string>): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - RegulaSync Report</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #1a1a2e; }
    .header { border-bottom: 3px solid #0066cc; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: #0066cc; margin: 0 0 10px 0; }
    .header .subtitle { color: #666; font-size: 14px; }
    .metadata { background: #f5f7fa; padding: 15px; border-radius: 8px; margin-bottom: 30px; }
    .metadata-item { display: inline-block; margin-right: 30px; }
    .metadata-label { font-weight: bold; color: #666; font-size: 12px; text-transform: uppercase; }
    .metadata-value { color: #1a1a2e; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #0066cc; color: white; padding: 12px; text-align: left; font-weight: 600; }
    td { padding: 10px 12px; border-bottom: 1px solid #e0e0e0; }
    tr:nth-child(even) { background: #f9f9f9; }
    .section { margin: 30px 0; }
    .section-title { color: #0066cc; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }
    .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .badge-critical { background: #fee2e2; color: #dc2626; }
    .badge-high { background: #fef3c7; color: #d97706; }
    .badge-medium { background: #dbeafe; color: #2563eb; }
    .badge-low { background: #dcfce7; color: #16a34a; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #666; font-size: 12px; }
    .summary-box { background: linear-gradient(135deg, #0066cc 0%, #004499 100%); color: white; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .summary-stat { display: inline-block; margin-right: 40px; }
    .summary-stat-value { font-size: 32px; font-weight: bold; }
    .summary-stat-label { font-size: 12px; opacity: 0.9; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="subtitle">Generated by RegulaSync - AI-Powered Governance Automation</div>
  </div>
  
  <div class="metadata">
    ${Object.entries(metadata).map(([key, value]) => `
      <div class="metadata-item">
        <div class="metadata-label">${key}</div>
        <div class="metadata-value">${value}</div>
      </div>
    `).join('')}
  </div>
  
  ${content}
  
  <div class="footer">
    <p>This report was automatically generated by RegulaSync. For questions or concerns, please contact your compliance team.</p>
    <p>© ${new Date().getFullYear()} RegulaSync - AI-Powered Governance Automation for UK Businesses</p>
  </div>
</body>
</html>`;
}

/**
 * Generate Compliance Report
 */
export async function generateComplianceReport(options?: {
  startDate?: Date;
  endDate?: Date;
  format?: 'html' | 'csv';
}): Promise<{ content: string; filename: string; mimeType: string }> {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const format = options?.format || 'html';
  const now = new Date();
  const startDate = options?.startDate || new Date(now.getFullYear(), now.getMonth() - 3, 1);
  const endDate = options?.endDate || now;

  // Get compliance records
  const records = await db.select()
    .from(complianceRecords)
    .where(
      and(
        gte(complianceRecords.createdAt, startDate),
        lte(complianceRecords.createdAt, endDate)
      )
    )
    .orderBy(desc(complianceRecords.createdAt));

  // Get policies for context
  const allPolicies = await db.select().from(policies);
  const policyMap = new Map(allPolicies.map(p => [p.id, p]));

  // Calculate statistics
  const totalRecords = records.length;
  const completedRecords = records.filter(r => r.complianceStatus === 'compliant').length;
  const avgScore = records.length > 0 
    ? Math.round(records.reduce((sum, r) => sum + (r.score || 0), 0) / records.length)
    : 0;
  const criticalFindings = records.filter(r => r.findings && String(r.findings).toLowerCase().includes('critical')).length;

  if (format === 'csv') {
    const headers = ['ID', 'Department', 'Policy', 'Status', 'Score', 'Findings', 'Last Assessment', 'Next Assessment', 'Created'];
    const rows = records.map(r => [
      String(r.id),
      r.department,
      policyMap.get(r.policyId || 0)?.title || 'N/A',
      r.complianceStatus,
      String(r.score || 0),
      r.findings || '',
      r.lastAssessmentDate ? new Date(r.lastAssessmentDate).toISOString().split('T')[0] : '',
      r.nextAssessmentDate ? new Date(r.nextAssessmentDate).toISOString().split('T')[0] : '',
      new Date(r.createdAt).toISOString().split('T')[0],
    ]);

    return {
      content: generateCSV(headers, rows),
      filename: `compliance-report-${now.toISOString().split('T')[0]}.csv`,
      mimeType: 'text/csv',
    };
  }

  // Generate HTML report
  const content = `
    <div class="summary-box">
      <div class="summary-stat">
        <div class="summary-stat-value">${totalRecords}</div>
        <div class="summary-stat-label">Total Records</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${completedRecords}</div>
        <div class="summary-stat-label">Completed</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${avgScore}%</div>
        <div class="summary-stat-label">Average Score</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${criticalFindings}</div>
        <div class="summary-stat-label">Critical Findings</div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Compliance Records</h2>
      <table>
        <thead>
          <tr>
            <th>Department</th>
            <th>Policy</th>
            <th>Status</th>
            <th>Score</th>
            <th>Last Assessment</th>
            <th>Next Assessment</th>
          </tr>
        </thead>
        <tbody>
          ${records.map(r => `
            <tr>
              <td>${r.department}</td>
              <td>${policyMap.get(r.policyId || 0)?.title || 'N/A'}</td>
              <td><span class="badge badge-${r.complianceStatus === 'compliant' ? 'low' : r.complianceStatus === 'non_compliant' ? 'critical' : 'medium'}">${r.complianceStatus}</span></td>
              <td>${r.score || 0}%</td>
              <td>${r.lastAssessmentDate ? new Date(r.lastAssessmentDate).toLocaleDateString() : '-'}</td>
              <td>${r.nextAssessmentDate ? new Date(r.nextAssessmentDate).toLocaleDateString() : '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `;

  return {
    content: generateHTMLReport('Compliance Report', content, {
      'Report Period': `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
      'Generated': now.toLocaleString(),
      'Total Records': String(totalRecords),
    }),
    filename: `compliance-report-${now.toISOString().split('T')[0]}.html`,
    mimeType: 'text/html',
  };
}

/**
 * Generate Audit Trail Report
 */
export async function generateAuditReport(options?: {
  startDate?: Date;
  endDate?: Date;
  entityType?: string;
  format?: 'html' | 'csv';
}): Promise<{ content: string; filename: string; mimeType: string }> {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const format = options?.format || 'html';
  const now = new Date();
  const startDate = options?.startDate || new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const endDate = options?.endDate || now;

  // Build query conditions
  let whereConditions = and(
    gte(auditTrail.createdAt, startDate),
    lte(auditTrail.createdAt, endDate)
  );

  if (options?.entityType) {
    whereConditions = and(
      whereConditions,
      eq(auditTrail.entityType, options.entityType)
    );
  }

  // Get audit entries
  const entries = await db.select()
    .from(auditTrail)
    .where(whereConditions)
    .orderBy(desc(auditTrail.createdAt))
    .limit(1000);

  // Calculate statistics
  const totalEntries = entries.length;
  const byAction = entries.reduce((acc, e) => {
    acc[e.action] = (acc[e.action] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  const verifiedEntries = entries.filter(e => e.hashValue).length;

  if (format === 'csv') {
    const headers = ['ID', 'Timestamp', 'Entity Type', 'Entity ID', 'Action', 'User', 'Hash', 'Previous Hash'];
    const rows = entries.map(e => [
      String(e.id),
      new Date(e.createdAt).toISOString(),
      e.entityType,
      String(e.entityId),
      e.action,
      e.userName || 'System',
      e.hashValue || '',
      e.previousHashValue || '',
    ]);

    return {
      content: generateCSV(headers, rows),
      filename: `audit-trail-${now.toISOString().split('T')[0]}.csv`,
      mimeType: 'text/csv',
    };
  }

  // Generate HTML report
  const content = `
    <div class="summary-box">
      <div class="summary-stat">
        <div class="summary-stat-value">${totalEntries}</div>
        <div class="summary-stat-label">Total Entries</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${verifiedEntries}</div>
        <div class="summary-stat-label">Hash Verified</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${Object.keys(byAction).length}</div>
        <div class="summary-stat-label">Action Types</div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Actions Summary</h2>
      <table>
        <thead>
          <tr>
            <th>Action</th>
            <th>Count</th>
            <th>Percentage</th>
          </tr>
        </thead>
        <tbody>
          ${Object.entries(byAction).map(([action, count]) => `
            <tr>
              <td>${action}</td>
              <td>${count}</td>
              <td>${Math.round((count / totalEntries) * 100)}%</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>

    <div class="section">
      <h2 class="section-title">Audit Trail Entries</h2>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Timestamp</th>
            <th>Entity</th>
            <th>Action</th>
            <th>User</th>
            <th>Hash Status</th>
          </tr>
        </thead>
        <tbody>
          ${entries.slice(0, 100).map(e => `
            <tr>
              <td>#${e.id}</td>
              <td>${new Date(e.createdAt).toLocaleString()}</td>
              <td>${e.entityType} #${e.entityId}</td>
              <td><span class="badge badge-medium">${e.action}</span></td>
              <td>${e.userName || 'System'}</td>
              <td>${e.hashValue ? '✓ Verified' : '○ Pending'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      ${entries.length > 100 ? `<p><em>Showing first 100 of ${entries.length} entries. Export to CSV for full data.</em></p>` : ''}
    </div>
  `;

  return {
    content: generateHTMLReport('Audit Trail Report', content, {
      'Report Period': `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
      'Generated': now.toLocaleString(),
      'Total Entries': String(totalEntries),
      'Chain Integrity': verifiedEntries === totalEntries ? 'Verified ✓' : `${verifiedEntries}/${totalEntries} verified`,
    }),
    filename: `audit-trail-${now.toISOString().split('T')[0]}.html`,
    mimeType: 'text/html',
  };
}

/**
 * Generate Policy Report
 */
export async function generatePolicyReport(options?: {
  category?: string;
  status?: string;
  format?: 'html' | 'csv';
}): Promise<{ content: string; filename: string; mimeType: string }> {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const format = options?.format || 'html';
  const now = new Date();

  // Get policies
  let allPolicies = await db.select().from(policies).orderBy(desc(policies.updatedAt));

  if (options?.category) {
    allPolicies = allPolicies.filter(p => p.category === options.category);
  }
  if (options?.status) {
    allPolicies = allPolicies.filter(p => p.status === options.status);
  }

  // Get users for owner names
  const allUsers = await db.select().from(users);
  const userMap = new Map(allUsers.map(u => [u.id, u]));

  // Calculate statistics
  const totalPolicies = allPolicies.length;
  const activePolicies = allPolicies.filter(p => p.status === 'active').length;
  const avgComplianceScore = allPolicies.length > 0
    ? Math.round(allPolicies.reduce((sum, p) => sum + (p.complianceScore || 0), 0) / allPolicies.length)
    : 0;
  const byCategory = allPolicies.reduce((acc, p) => {
    acc[p.category] = (acc[p.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  if (format === 'csv') {
    const headers = ['ID', 'Title', 'Category', 'Status', 'Priority', 'Owner', 'Compliance Score', 'Effective Date', 'Review Date', 'Version'];
    const rows = allPolicies.map(p => [
      String(p.id),
      p.title,
      p.category,
      p.status,
      p.priority,
      userMap.get(p.ownerId || 0)?.name || 'Unassigned',
      String(p.complianceScore || 0),
      p.effectiveDate ? new Date(p.effectiveDate).toISOString().split('T')[0] : '',
      p.reviewDate ? new Date(p.reviewDate).toISOString().split('T')[0] : '',
      String(p.version || 1),
    ]);

    return {
      content: generateCSV(headers, rows),
      filename: `policy-report-${now.toISOString().split('T')[0]}.csv`,
      mimeType: 'text/csv',
    };
  }

  // Generate HTML report
  const content = `
    <div class="summary-box">
      <div class="summary-stat">
        <div class="summary-stat-value">${totalPolicies}</div>
        <div class="summary-stat-label">Total Policies</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${activePolicies}</div>
        <div class="summary-stat-label">Active</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${avgComplianceScore}%</div>
        <div class="summary-stat-label">Avg Compliance</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${Object.keys(byCategory).length}</div>
        <div class="summary-stat-label">Categories</div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Policies by Category</h2>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Count</th>
            <th>Percentage</th>
          </tr>
        </thead>
        <tbody>
          ${Object.entries(byCategory).map(([category, count]) => `
            <tr>
              <td>${category.replace(/_/g, ' ')}</td>
              <td>${count}</td>
              <td>${Math.round((count / totalPolicies) * 100)}%</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>

    <div class="section">
      <h2 class="section-title">Policy Details</h2>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Status</th>
            <th>Priority</th>
            <th>Owner</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          ${allPolicies.map(p => `
            <tr>
              <td>${p.title}</td>
              <td>${p.category.replace(/_/g, ' ')}</td>
              <td><span class="badge badge-${p.status === 'active' ? 'low' : p.status === 'draft' ? 'medium' : 'high'}">${p.status}</span></td>
              <td><span class="badge badge-${p.priority}">${p.priority}</span></td>
              <td>${userMap.get(p.ownerId || 0)?.name || 'Unassigned'}</td>
              <td>${p.complianceScore || 0}%</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `;

  return {
    content: generateHTMLReport('Policy Report', content, {
      'Generated': now.toLocaleString(),
      'Total Policies': String(totalPolicies),
      'Active Policies': String(activePolicies),
    }),
    filename: `policy-report-${now.toISOString().split('T')[0]}.html`,
    mimeType: 'text/html',
  };
}

/**
 * Generate Regulatory Impact Report
 */
export async function generateRegulatoryReport(options?: {
  startDate?: Date;
  endDate?: Date;
  format?: 'html' | 'csv';
}): Promise<{ content: string; filename: string; mimeType: string }> {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const format = options?.format || 'html';
  const now = new Date();
  const startDate = options?.startDate || new Date(now.getFullYear(), 0, 1);
  const endDate = options?.endDate || now;

  // Get regulatory updates
  const updates = await db.select()
    .from(regulatoryUpdates)
    .where(
      and(
        gte(regulatoryUpdates.createdAt, startDate),
        lte(regulatoryUpdates.createdAt, endDate)
      )
    )
    .orderBy(desc(regulatoryUpdates.createdAt));

  // Get AI recommendations
  const recommendations = await db.select()
    .from(aiRecommendations)
    .where(eq(aiRecommendations.category, 'regulatory_change'))
    .orderBy(desc(aiRecommendations.createdAt));

  // Calculate statistics
  const totalUpdates = updates.length;
  const criticalUpdates = updates.filter(u => u.impactLevel === 'critical').length;
  const highUpdates = updates.filter(u => u.impactLevel === 'high').length;
  const implementedUpdates = updates.filter(u => u.status === 'implemented').length;
  const pendingRecommendations = recommendations.filter(r => r.status === 'new').length;

  if (format === 'csv') {
    const headers = ['ID', 'Title', 'Source', 'Regulatory Body', 'Impact Level', 'Status', 'Effective Date', 'Created'];
    const rows = updates.map(u => [
      String(u.id),
      u.title,
      u.source || '',
      u.regulatoryBody || '',
      u.impactLevel,
      u.status,
      u.effectiveDate ? new Date(u.effectiveDate).toISOString().split('T')[0] : '',
      new Date(u.createdAt).toISOString().split('T')[0],
    ]);

    return {
      content: generateCSV(headers, rows),
      filename: `regulatory-report-${now.toISOString().split('T')[0]}.csv`,
      mimeType: 'text/csv',
    };
  }

  // Generate HTML report
  const content = `
    <div class="summary-box">
      <div class="summary-stat">
        <div class="summary-stat-value">${totalUpdates}</div>
        <div class="summary-stat-label">Total Updates</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${criticalUpdates}</div>
        <div class="summary-stat-label">Critical</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${highUpdates}</div>
        <div class="summary-stat-label">High Impact</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${implementedUpdates}</div>
        <div class="summary-stat-label">Implemented</div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Regulatory Updates</h2>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Source</th>
            <th>Impact</th>
            <th>Status</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          ${updates.map(u => `
            <tr>
              <td>${u.title}</td>
              <td>${u.regulatoryBody || u.source || 'Unknown'}</td>
              <td><span class="badge badge-${u.impactLevel}">${u.impactLevel}</span></td>
              <td>${u.status}</td>
              <td>${new Date(u.createdAt).toLocaleDateString()}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>

    ${pendingRecommendations > 0 ? `
    <div class="section">
      <h2 class="section-title">Pending AI Recommendations (${pendingRecommendations})</h2>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Priority</th>
            <th>Confidence</th>
            <th>Created</th>
          </tr>
        </thead>
        <tbody>
          ${recommendations.filter(r => r.status === 'new').slice(0, 10).map(r => `
            <tr>
              <td>${r.title}</td>
              <td><span class="badge badge-${r.priority}">${r.priority}</span></td>
              <td>${r.confidenceScore || 0}%</td>
              <td>${new Date(r.createdAt).toLocaleDateString()}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    ` : ''}
  `;

  return {
    content: generateHTMLReport('Regulatory Impact Report', content, {
      'Report Period': `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
      'Generated': now.toLocaleString(),
      'Total Updates': String(totalUpdates),
      'Pending Actions': String(pendingRecommendations),
    }),
    filename: `regulatory-report-${now.toISOString().split('T')[0]}.html`,
    mimeType: 'text/html',
  };
}

/**
 * Generate Executive Summary Report
 */
export async function generateExecutiveSummary(): Promise<{ content: string; filename: string; mimeType: string }> {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const now = new Date();

  // Get all key metrics
  const allPolicies = await db.select().from(policies);
  const allCompliance = await db.select().from(complianceRecords);
  const allUpdates = await db.select().from(regulatoryUpdates);
  const allRecommendations = await db.select().from(aiRecommendations);
  const allDelegations = await db.select().from(delegationAuthority);

  // Calculate metrics
  const activePolicies = allPolicies.filter(p => p.status === 'active').length;
  const avgComplianceScore = allPolicies.length > 0
    ? Math.round(allPolicies.reduce((sum, p) => sum + (p.complianceScore || 0), 0) / allPolicies.length)
    : 0;
  const pendingActions = allRecommendations.filter(r => r.status === 'new').length;
  const criticalUpdates = allUpdates.filter(u => u.impactLevel === 'critical' && u.status !== 'implemented').length;
  const activeDelegations = allDelegations.filter(d => d.status === 'active').length;
  const overdueCompliance = allCompliance.filter(c => c.complianceStatus === 'non_compliant').length;

  const content = `
    <div class="summary-box">
      <div class="summary-stat">
        <div class="summary-stat-value">${avgComplianceScore}%</div>
        <div class="summary-stat-label">Overall Compliance</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${activePolicies}</div>
        <div class="summary-stat-label">Active Policies</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${pendingActions}</div>
        <div class="summary-stat-label">Pending Actions</div>
      </div>
      <div class="summary-stat">
        <div class="summary-stat-value">${criticalUpdates}</div>
        <div class="summary-stat-label">Critical Updates</div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Key Metrics Overview</h2>
      <table>
        <thead>
          <tr>
            <th>Metric</th>
            <th>Value</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Total Policies</td>
            <td>${allPolicies.length}</td>
            <td><span class="badge badge-low">Active</span></td>
          </tr>
          <tr>
            <td>Active Policies</td>
            <td>${activePolicies}</td>
            <td><span class="badge badge-low">Good</span></td>
          </tr>
          <tr>
            <td>Average Compliance Score</td>
            <td>${avgComplianceScore}%</td>
            <td><span class="badge badge-${avgComplianceScore >= 80 ? 'low' : avgComplianceScore >= 60 ? 'medium' : 'high'}">${avgComplianceScore >= 80 ? 'Good' : avgComplianceScore >= 60 ? 'Fair' : 'Needs Attention'}</span></td>
          </tr>
          <tr>
            <td>Regulatory Updates</td>
            <td>${allUpdates.length}</td>
            <td><span class="badge badge-medium">Monitored</span></td>
          </tr>
          <tr>
            <td>Critical Updates Pending</td>
            <td>${criticalUpdates}</td>
            <td><span class="badge badge-${criticalUpdates > 0 ? 'critical' : 'low'}">${criticalUpdates > 0 ? 'Action Required' : 'Clear'}</span></td>
          </tr>
          <tr>
            <td>AI Recommendations Pending</td>
            <td>${pendingActions}</td>
            <td><span class="badge badge-${pendingActions > 5 ? 'high' : pendingActions > 0 ? 'medium' : 'low'}">${pendingActions > 5 ? 'Review Needed' : pendingActions > 0 ? 'Pending' : 'Clear'}</span></td>
          </tr>
          <tr>
            <td>Active Delegations</td>
            <td>${activeDelegations}</td>
            <td><span class="badge badge-low">Active</span></td>
          </tr>
          <tr>
            <td>Overdue Compliance Items</td>
            <td>${overdueCompliance}</td>
            <td><span class="badge badge-${overdueCompliance > 0 ? 'critical' : 'low'}">${overdueCompliance > 0 ? 'Overdue' : 'On Track'}</span></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="section">
      <h2 class="section-title">Recommendations</h2>
      <ul>
        ${criticalUpdates > 0 ? '<li><strong>Critical:</strong> Review and implement critical regulatory updates immediately.</li>' : ''}
        ${overdueCompliance > 0 ? '<li><strong>High:</strong> Address overdue compliance items to maintain regulatory standing.</li>' : ''}
        ${pendingActions > 5 ? '<li><strong>Medium:</strong> Review AI-generated recommendations to improve compliance posture.</li>' : ''}
        ${avgComplianceScore < 80 ? '<li><strong>Medium:</strong> Focus on improving overall compliance score through policy updates.</li>' : ''}
        <li><strong>Ongoing:</strong> Continue monitoring regulatory feeds for new updates.</li>
      </ul>
    </div>
  `;

  return {
    content: generateHTMLReport('Executive Summary', content, {
      'Generated': now.toLocaleString(),
      'Compliance Score': `${avgComplianceScore}%`,
      'Pending Actions': String(pendingActions),
    }),
    filename: `executive-summary-${now.toISOString().split('T')[0]}.html`,
    mimeType: 'text/html',
  };
}
